### ISSUE TITLE
Colored output not working on Windows

### ISSUE THREAD

**Issue by askar882** [zhovner/mfdread#12]
ANSI escape character sequences not working properly on Windows. Instead of colored output, I
got random codes on my Powershell console. Here is a sample output below.
![image](https://user-images.githubusercontent.com/17901680/66717803-b596f480-ee0f-11e9-9fda-163e38b5b6d4.png)
But everything worked fine when I implemented [colorama](https://pypi.org/project/colorama) module. So, I'm hoping you could implement this module in your project.

**Comment by zhovner** [comment]
Because this characters is bash colors. You can use it in bash in windows subsystem linux.

>everything worked fine when I implemented colorama module
I'm trying to minimize 3rd party modules needed.
