### ISSUE TITLE
   Will display abnormally.        Windows 10     cmd.exe/powershell.exe    

### ISSUE THREAD

**Issue by soldierbro** [zhovner/mfdread#16]
![图片](https://user-images.githubusercontent.com/26686160/206623072-c90e0fcf-d709-4c8b-b955-d8ce7a7ee0ac.png)

![图片](https://user-images.githubusercontent.com/26686160/206623357-3457cca6-6fce-4a3a-9d61-7eea8935e985.png)

**Comment by zhovner** [comment]
It's a bash colors. Try WSL
